using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_UI.Models
{
    public class VMProject
    {
        //autogenerated id from db
        public int? Id { get; set; }

        //name of the project
        public string Title { get; set; }

        //description of the project
        public string Description { get; set; }
        //Selected admin of the project
        public VMUser LeaderUser { get; set; }
        //list of assigned users to the project
        public List<VMUser> Members { get; set; }
        //list of assigned tasks to the project
        public List<VMTask> Tasks { get; set; }
        //Date for project was created
        public DateTime CreadtedDate { get; set; }
        //Date for project was last changed
        public DateTime LastChangedDate { get; set; }

        public VMProject()
        {
           
        }
        public VMProject(int id)
        {
            this.Id = id;
            this.Title = "something?";
        }
    }
    
}