using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web_UI.Models
{
    public class VMProject
    {
        //autogenerated id from db
        public int? Id { get; set; }
        //name of the project
        [Required]
        public string Title { get; set; }
        //description of the project
        [Required]
        public string Description { get; set; }
        //Selected admin of the project
        public VMUser LeaderUser { get; set; }
        //list of assigned users to the project
        public List<VMUser> Members { get; set; }
        //list of assigned tasks to the project
        public List<VMTask> Tasks { get; set; }
        //Date for project was created
        [DataType(DataType.Date)]
        [DisplayName("Created on")]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime CreadtedDate { get; set; }
        //Date for project was last changed
        [DataType(DataType.Date)]
        [DisplayName("Last changed")]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime LastChangedDate { get; set; }
        public bool Done { get; set; }

        public VMProject()
        {

        }
        public VMProject(int id)
        {
            this.Id = id;
            this.Title = "something?";
        }
        public VMProject(int? id, string title, string desc, DateTime cd, DateTime lcd, bool done)
        {
            this.Id = id;
            this.Title = title;
            this.Description = desc;
            this.CreadtedDate = cd;
            this.LastChangedDate = lcd;
            this.Done = done;
        }
    }

}