using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;

//using Web_UI.Models;

namespace Logic.Models
{
    [Table]
    public class Project
    {
        //autogenerated id from db
        [Column(Name = "id", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id { get; set; }

        //name of the project
        [Column(Name = "title")]
        public string Title { get; set; }

        //description of the project
        [Column(Name = "description")]
        public string Description { get; set; }
        //Selected admin of the project
        public User LeaderUser { get; set; }
        //list of assigned users to the project
        public List<User> Members { get; set; }
        //list of assigned tasks to the project
        public List<Task> Tasks { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime LastChangeDateTime { get; set; }

    }
}